In [5]:
# 1.solution:
import numpy as np
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [7]:
arr1=np.random.rand(3,3)
print(arr1)

[[0.38366606 0.23726945 0.46324779]
 [0.65998847 0.17389267 0.99933128]
 [0.19648544 0.08775124 0.62769608]]


In [13]:
#2.	Array Attributes
print('array shape: ',arr1.shape)
print('array size: ',arr1.size)
print('array data type: ',arr1.dtype)

array shape:  (3, 3)
array size:  9
array data type:  float64


In [19]:
#3.	Basic Operations
arr2=5+arr
print(arr2)
print(arr1*arr1)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[0.14719965 0.05629679 0.21459852]
 [0.43558478 0.03023866 0.998663  ]
 [0.03860653 0.00770028 0.39400237]]


In [27]:
#4.	Indexing and Slicing
array=np.arange(1,26).reshape(5,5)
print(array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[1 2 3 4 5]]


In [29]:
print(array[0:1,:])

[[1 2 3 4 5]]


In [33]:
print(array[4:5,:])

[[21 22 23 24 25]]


In [39]:
print(array[0:3,0:2])

[[ 1  2]
 [ 6  7]
 [11 12]]


In [63]:
#5.Aggregation
ar=np.random.randint(1,100,10)
print(ar)
print('max value: ',np.max(ar))
print('min value: ',np.min(ar))
print('mean value: ',np.mean(ar))
print('standard deviation value: ',np.std(ar))

[77 97 50 57 34 46 83 17 55 72]
max value:  97
min value:  17
mean value:  58.8
standard deviation value:  22.741152125607005


In [73]:
#6.	Reshaping
arr=np.arange(1,13)
print(arr)
print('after reshaping')
arr1=arr.reshape(3,4)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
after reshaping
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [91]:
#7.	Broadcasting
ones=np.ones(9)
ar=ones.reshape(3,3)
print(ar)
# np.ones((3,3)) is also correct
array=[1,2,3]
print('sum:')
print(ar+array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
sum:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [113]:
#8.	Filtering
ra=np.arange(1,51)
print(ra)
print('divisible by 5:')
for i in ra:
    if i%5==0:
        result=ra[i-1]
        print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
divisible by 5:
5
10
15
20
25
30
35
40
45
50


In [131]:
#9.	Matrix Multiplication
arr1=np.random.randint(1,20,(3,3))
arr2=np.random.randint(1,15,(3,3))
print('multiplication: \n',np.dot(arr1,arr2))

multiplication: 
 [[319 193 313]
 [181 249 243]
 [433 421 471]]


In [147]:
#10.Advanced Indexing
arr3=np.random.randint(1,20,(4,4))
print(arr3)
# diagonal_elements=np.diagonal(arr3)
# print('diagonal_elements: \n',diagonal_elements)
rows=np.array([0,1,2,3])
cols=np.array([0,1,2,3])
de=arr3[rows,cols]
print('diagonal_elements: \n',de)

[[12  6 17 16]
 [18 12 16 10]
 [ 8  8  5 13]
 [ 8  4  1  5]]
diagonal_elements: 
 [12 12  5  5]
